server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: ${BBDD_URL}
    password: ${BBDD_PWD}
    username: ${BBDD_USER}
    platform: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
